name: Ruby

on:
  push:
    paths:
    - '.github/workflows/ruby.yml'
    - '.ruby-version'
    - 'bin/test'
    - 'Gemfile'
    - 'Gemfile.lock'

jobs:
  test_2_0:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        key: [foo, bar]
    container:
      image: ruby:2.0
      env:
        LANG: C.UTF-8
    steps:
      - uses: actions/checkout@v2
      - run: ruby -v
      - run: bundle -v
      - run: echo $CI
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: ruby/setup-ruby@v1
      with:
        bundler: "Gemfile.lock"
        bundler-cache: true
    - run:  ruby -v
    - run:  bundle -v
    - run:  gem -v
    - run:  bin/test
    - run:  bundle install
