name: Ruby

on:
  push:
    paths:
    - '.github/workflows/ruby.yml'
    - '.ruby-version'
    - 'bin/test'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: ruby/setup-ruby@v1
    - run:  ruby -v
    - run:  bundle -v
    - run:  gem -v
    - run:  bin/test
