name: Ruby

on:
  push:
    paths:
    - '.github/workflows/ruby.yml'
    - '.ruby-version'
    - 'bin/test'
    - 'Gemfile'
    - 'Gemfile.lock'

jobs:
  windows:
    runs-on: windows-latest
    continue-on-error: true
    strategy:
      fail-fast: false
      matrix:
        ruby: [2.1, 2.2, 2.3, 2.4, 2.5, 2.6, 2.7, '3.0', head, mingw, mswin]
    steps:
      - run: ruby -v
      - run: ruby -e 'p RUBY_ENGINE'
      - run: ruby -e 'p RUBY_PLATFORM'
      - run: ruby -e 'p RUBY_DESCRIPTION'
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: ruby/setup-ruby@v1
      with:
        bundler: "Gemfile.lock"
        bundler-cache: true
    - run:  ruby -v
    - run:  bundle -v
    - run:  gem -v
    - run:  bin/test
    - run:  bundle install
